easy_admin:
    design:
        menu:
            - { entity: 'Subdivision', label: 'menu.subdivisions', default: true }
            - { entity: 'Department', label: 'menu.departments' }
            - { entity: 'Phone', label: 'menu.phones' }
            - { entity: 'Employee', label: 'menu.employees' }
    entities:
        Subdivision:
            class: App\Entity\Subdivision
            form:
                fields:
                    - name
                    - { property: 'priority', type_options: { attr: { value: '0', min: 0, max: 99 } } }
                    - { property: 'departments', type_options: { disabled: true } }
        Department:
            class: App\Entity\Department
            form:
                fields:
                    - name
                    - { property: 'priority', type_options: { attr: { value: '0', min: 0, max: 99 } } }
                    - subdivision
                    - { property: 'phones', type_options: { disabled: true } }
        Phone:
            class: App\Entity\Phone
            form:
                fields:
                    - { property: 'priority', type_options: { attr: { value: '0', min: 0, max: 99 } } }
                    - phoneNumber
                    - alternateNumber
                    - cabinets
                    - employees
                    - department
        Employee:
            class: App\Entity\Employee
            form:
                fields:
                    - lastName
                    - firstName
                    - middleName
                    - position
                    - cellphoneNumbers
                    - phones