easy_admin:
    entities:
        Department:
            class: App\Entity\Department
            label: 'admin.label.department'
            list:
                title: 'admin.title.list.department'
                sort: 'updatedAt'
                fields:
                    - { property: 'id', label: 'admin.field.id' }
                    - { property: 'priority', label: 'admin.field.priority' }
                    - { property: 'name', label: 'admin.field.name' }
                    - { property: 'phones', label: 'admin.field.phones' }
                    - { property: 'subdivision', label: 'admin.field.subdivision' }
                    - { property: 'updatedAt', label: 'admin.field.updated_at' }
            form:
                fields:
                    - { property: 'id', label: 'admin.field.id', type_options: { disabled: true } }
                    - { property: 'priority', label: 'admin.field.priority', type_options: { attr: { min: 0, max: 99 } } }
                    - { property: 'name', label: 'admin.field.name' }
                    - { property: 'phones', label: 'admin.field.phones', type_options: { disabled: true } }
                    - { property: 'subdivision', label: 'admin.field.subdivision' }
                    - { property: 'createdAt', label: 'admin.field.created_at', type_options: { disabled: true } }
                    - { property: 'updatedAt', label: 'admin.field.updated_at', type_options: { disabled: true } }
            new:
                title: 'admin.title.new.department'
                fields:
                    - '-id'
                    - '-createdAt'
                    - '-updatedAt'