easy_admin:
    entities:
        Department:
            class: App\Entity\Department
            list:
                title: 'Список отделов'
                sort: 'updatedAt'
                fields:
                    - { property: 'id', label: 'field.id' }
                    - { property: 'priority', label: 'field.priority' }
                    - { property: 'name', label: 'field.name' }
                    - { property: 'phones', label: 'field.phones' }
                    - { property: 'subdivision', label: 'field.subdivision' }
                    - { property: 'updatedAt', label: 'field.updated_at' }
            form:
                fields:
                    - { property: 'id', label: 'field.id', type_options: { disabled: true } }
                    - { property: 'priority', label: 'field.priority', type_options: { attr: { min: 0, max: 99 } } }
                    - { property: 'name', label: 'field.name' }
                    - { property: 'phones', label: 'field.phones', type_options: { disabled: true } }
                    - { property: 'subdivision', label: 'field.subdivision' }
                    - { property: 'createdAt', label: 'field.created_at', type_options: { disabled: true } }
                    - { property: 'updatedAt', label: 'field.updated_at', type_options: { disabled: true } }
            new:
                title: 'Новый номер телефона'
                fields:
                    - '-id'
                    - '-createdAt'
                    - '-updatedAt'