easy_admin:
    entities:
        Employee:
            class: App\Entity\Employee
            list:
                title: 'Список сотрудников'
                sort: 'updatedAt'
                fields:
                    - { property: 'id', label: 'admin.field.id' }
                    - { property: 'fullname', label: 'admin.field.fullname' }
                    - { property: 'position', label: 'admin.field.position' }
                    - { property: 'cellphoneNumbers', label: 'admin.field.cellphone_numbers' }
                    - { property: 'phones', label: 'admin.field.phones' }
                    - { property: 'updatedAt', label: 'admin.field.updated_at' }
            form:
                fields:
                    - { property: 'id', label: 'admin.field.id', type_options: { disabled: true } }
                    - { property: 'lastName', label: 'admin.field.lastName' }
                    - { property: 'firstName', label: 'admin.field.firstName' }
                    - { property: 'middleName', label: 'admin.field.middleName' }
                    - { property: 'position', label: 'admin.field.position' }
                    - { property: 'cellphoneNumbers', label: 'admin.field.cellphone_numbers' }
                    - { property: 'phones', label: 'admin.field.phones', type_options: { by_reference: false} }
                    - { property: 'createdAt', label: 'admin.field.created_at', type_options: { disabled: true } }
                    - { property: 'updatedAt', label: 'admin.field.updated_at', type_options: { disabled: true } }
            new:
                fields:
                    - '-id'
                    - '-createdAt'
                    - '-updatedAt'