easy_admin:
    entities:
        Phone:
            class: App\Entity\Phone
            label: 'admin.label.phone'
            list:
                title: 'admin.title.list.phone'
                sort: 'updatedAt'
                fields:
                    - { property: 'id', label: 'admin.field.id' }
                    - { property: 'priority', label: 'admin.field.priority' }
                    - { property: 'phoneNumber', label: 'admin.field.phone_number' }
                    - { property: 'alternateNumber', label: 'admin.field.alternate_number' }
                    - { property: 'cabinets', label: 'admin.field.cabinets' }
                    - { property: 'employees', label: 'admin.field.employees' }
                    - { property: 'department', label: 'admin.field.department' }
                    - { property: 'updatedAt', label: 'admin.field.updated_at' }
            search:
                fields:
                    - { property: 'id' }
                    - { property: 'priority' }
                    - { property: 'phoneNumber' }
                    - { property: 'alternateNumber' }
                    - { property: 'cabinets' }
                    - { property: 'department.name' }
            form:
                fields:
                    - { property: 'id', label: 'admin.field.id', type_options: { disabled: true } }
                    - { property: 'priority', label: 'admin.field.priority', type_options: { attr: { min: 0, max: 99 } } }
                    - { property: 'phoneNumber', label: 'admin.field.phone_number' }
                    - { property: 'alternateNumber', label: 'admin.field.alternate_number' }
                    - { property: 'cabinets', label: 'admin.field.cabinets' }
                    - { property: 'employees', label: 'admin.field.employees' }
                    - { property: 'department', label: 'admin.field.department' }
                    - { property: 'createdAt', label: 'admin.field.created_at', type_options: { widget: 'single_text', required: false, disabled: true } }
                    - { property: 'updatedAt', label: 'admin.field.updated_at', type_options: { widget: 'single_text', required: false, disabled: true } }
            new:
                title: 'admin.title.new.phone'
                fields:
                    - '-id'
                    - '-createdAt'
                    - '-updatedAt'