easy_admin:
    entities:
        Subdivision:
            class: App\Entity\Subdivision
            label: 'admin.label.subdivision'
            list:
                title: 'admin.title.list.subdivision'
                sort: 'updatedAt'
                fields:
                    - { property: 'id', label: 'admin.field.id' }
                    - { property: 'priority', label: 'admin.field.priority' }
                    - { property: 'name', label: 'admin.field.name' }
                    - { property: 'departments', label: 'admin.field.departments' }
                    - { property: 'updatedAt', label: 'admin.field.updated_at' }
            form:
                fields:
                    - { property: 'id', label: 'admin.field.id', type_options: { disabled: true } }
                    - { property: 'priority', label: 'admin.field.priority', type_options: { attr: { min: 0, max: 99 } } }
                    - { property: 'name', label: 'admin.field.name' }
                    - { property: 'departments', label: 'admin.field.departments', type_options: { disabled: true } }
                    - { property: 'createdAt', label: 'admin.field.created_at', type_options: { widget: 'single_text', required: false, disabled: true } }
                    - { property: 'updatedAt', label: 'admin.field.updated_at', type_options: { widget: 'single_text', required: false, disabled: true } }
            new:
                title: 'admin.title.new.subdivision'
                fields:
                    - '-id'
                    - '-createdAt'
                    - '-updatedAt'