easy_admin:
    list:
        actions:
            - { name: 'new', icon: 'plus', label: 'button.new' }
            - { name: 'edit', label: 'button.edit' }
            - { name: 'delete', icon: 'trash', label: false, title: 'button.delete' }