easy_admin:
    design:
        menu:
            - { entity: 'Subdivision', label: 'admin.menu.subdivisions', icon: 'building', default: true }
            - { entity: 'Department', label: 'admin.menu.departments', icon: 'user-friends' }
            - { entity: 'Phone', label: 'admin.menu.phones', icon: 'phone-square' }
            - { entity: 'Employee', label: 'admin.menu.employees', icon: 'address-card' }